# Generated by Django 2.0.5 on 2018-06-12 03:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysession', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUserAvatar',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mysession.AuthUser', unique=True)),
                ('avatar', models.ImageField(blank=True, upload_to='image_profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='authuserprofile',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='authuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 12, 10, 52, 27, 579525)),
        ),
    ]
